#!/bin/bash
TARGET=$1
SRC_DIR=$2
OBJ_DIR=$3/$1
INSTALL_DIR=$4/$1

. ./env.sh $TARGET

CMAKE_OPTION="-DARCH_TRIPLE=$TARGET -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR"

CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_C_COMPILER=$CC"
CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_CXX_COMPILER=$CXX"
CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_AS=$AS"
CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_AR=$AR"
CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_LD=$LD"
CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_ASM_COMPILER=$XAS"
CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_LINKER=$LD"
CMAKE_OPTION="$CMAKE_OPTION -DCMAKE_RANLIB=$RANLIB"

mkdir -p $OBJ_DIR
cd $OBJ_DIR
cmake $SRC_DIR  $CMAKE_OPTION
make VERBOSE=1
#make VERBOSE=1 install

